# Generated by Django 3.1.4 on 2021-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=70)),
                ('gmail', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('balance', models.CharField(max_length=70)),
                ('pending', models.CharField(max_length=70)),
                ('fine', models.CharField(max_length=70)),
            ],
        ),
    ]
